### ISSUE TITLE
error in habitat-sim

### ISSUE THREAD

**Issue by pioneer-innovation** [ziadalh/zero_experience_required#2]
Hi,
 when I run `python setup.py install --headless --with-cuda` to install habitat-sim, it returns error:
        
    th-cuda
    running install
    running bdist_egg
    running egg_info
    writing habitat_sim.egg-info/PKG-INFO
    writing dependency_links to habitat_sim.egg-info/dependency_links.txt
    writing requirements to habitat_sim.egg-info/requires.txt
    writing top-level names to habitat_sim.egg-info/top_level.txt
    reading manifest file 'habitat_sim.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'LICENSE'
    writing manifest file 'habitat_sim.egg-info/SOURCES.txt'
    installing library code to build/bdist.linux-x86_64/egg
    running install_lib
    running build_py
    running build_ext
    error: [Errno 2] No such file or directory: 'build/compile_commands.json'

**Comment by ziadalh** [comment]
I couldn't reproduce the reported error ... Can you provide more context? Did you follow the steps in the READEM?
