### ISSUE TITLE
Question about your Object Nav dataset

### ISSUE THREAD

**Issue by soyeonm** [ziadalh/zero_experience_required#3]
Hello,

In your ObjectNav for Gibson, is the same dataset used in the ObjectNav Habitat challenge (https://aihabitat.org/challenge/2021/) used? Are the validation tasks themselves same other than the agent height?

**Comment by ziadalh** [comment]
You can download the objectnav/gibson datasets used in this study from the datasets section in the [README](https://github.com/ziadalh/zero_experience_required/#datasets). The agent configuration can be found [here](https://github.com/ziadalh/zero_experience_required/blob/main/config/imagenav/gibson/imagenav_rgb.yaml)
